from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Any, Dict, Optional, Sequence

from .moire_errors import MoReWorkflowError


def _read_lammps_atom_records(data_lmp: Path) -> list[Dict[str, Any]]:
    if not data_lmp.exists():
        raise MoReWorkflowError(f"data.lmp not found: {data_lmp}")
    lines = data_lmp.read_text(encoding="utf-8", errors="replace").splitlines()
    try:
        start = next(index for index, raw in enumerate(lines) if raw.strip() == "Atoms")
    except StopIteration as exc:
        raise MoReWorkflowError(f"Could not find an 'Atoms' section in {data_lmp}") from exc

    records: list[Dict[str, Any]] = []
    for raw in lines[start + 1 :]:
        line = raw.strip()
        if not line:
            if records:
                break
            continue
        if line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 5:
            continue
        try:
            atom_id = int(parts[0])
            atom_type = int(parts[1])
            x, y, z = (float(parts[2]), float(parts[3]), float(parts[4]))
        except ValueError:
            continue
        records.append(
            {
                "atom_id": atom_id,
                "atom_type": atom_type,
                "x": x,
                "y": y,
                "z": z,
            }
        )
    if not records:
        raise MoReWorkflowError(f"Could not parse any atoms from {data_lmp}")
    return records


def _read_final_mosia_records(final_mosia: Path) -> list[Dict[str, Any]]:
    if not final_mosia.exists():
        raise MoReWorkflowError(f"final.mosia not found: {final_mosia}")
    lines = final_mosia.read_text(encoding="utf-8", errors="replace").splitlines()
    records: list[Dict[str, Any]] = []
    for raw in lines[1:]:
        line = raw.strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) < 4:
            continue
        try:
            atom_id = int(parts[0])
            x, y, z = (float(parts[1]), float(parts[2]), float(parts[3]))
        except ValueError:
            continue
        records.append(
            {
                "atom_id": atom_id,
                "x": x,
                "y": y,
                "z": z,
            }
        )
    if not records:
        raise MoReWorkflowError(f"Could not parse any atom coordinates from {final_mosia}")
    return records


def _atom_label(atom_type: Optional[int]) -> str:
    if atom_type is None:
        return "X"
    return f"T{int(atom_type)}"


def _write_xyz_snapshot(path: Path, atoms: Sequence[Dict[str, Any]]) -> str:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [str(len(atoms)), f"generated by mietclaw: {path.name}"]
    for atom in atoms:
        lines.append(
            f"{_atom_label(atom.get('atom_type'))} "
            f"{float(atom['x']):.8f} {float(atom['y']):.8f} {float(atom['z']):.8f}"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return str(path)


def _build_lammps_visualization_inputs(*, copied_case_dir: Path) -> Dict[str, Any]:
    data_lmp = copied_case_dir / "data.lmp"
    final_mosia = copied_case_dir / "final.mosia"
    initial_atoms = _read_lammps_atom_records(data_lmp)
    atom_types = {int(atom["atom_id"]): int(atom["atom_type"]) for atom in initial_atoms}
    final_positions = _read_final_mosia_records(final_mosia)
    final_atoms = [
        {
            "atom_id": int(item["atom_id"]),
            "atom_type": atom_types.get(int(item["atom_id"])),
            "x": float(item["x"]),
            "y": float(item["y"]),
            "z": float(item["z"]),
        }
        for item in final_positions
    ]
    initial_xyz = _write_xyz_snapshot(copied_case_dir / "ovito_initial.xyz", initial_atoms)
    final_xyz = _write_xyz_snapshot(copied_case_dir / "ovito_final.xyz", final_atoms)
    return {
        "initial_structure": initial_xyz,
        "final_structure": final_xyz,
        "initial_particle_count": len(initial_atoms),
        "final_particle_count": len(final_atoms),
        "source_data_lmp": str(data_lmp),
        "source_final_mosia": str(final_mosia),
    }


def _list_dump_paths(run_dir: Path) -> list[Path]:
    candidates: list[Path] = []
    for pattern in ("*.dump", "*.k.dump.vacancy"):
        candidates.extend(run_dir.glob(pattern))
    unique = {item.resolve(): item for item in candidates}
    if not unique:
        return []

    def _sort_key(path: Path) -> tuple[int, str]:
        prefix = path.name.split(".", 1)[0]
        return (int(prefix) if prefix.isdigit() else 10**9, path.name)

    return sorted(unique.values(), key=_sort_key)

def _latest_dump_path(run_dir: Path) -> Optional[Path]:
    candidates = _list_dump_paths(run_dir)
    if not candidates:
        return None
    return candidates[-1]


def _render_ovito_snapshot(dump_path: Path, output_path: Path, python_cmd: str) -> Dict[str, Any]:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    script = """
import sys
import warnings
warnings.filterwarnings('ignore', message='.*OVITO.*PyPI')
from ovito.io import import_file
from ovito.vis import TachyonRenderer, Viewport

dump_path = sys.argv[1]
output_path = sys.argv[2]

pipeline = import_file(dump_path, multiple_frames=True)
pipeline.add_to_scene()
frame = max(pipeline.source.num_frames - 1, 0)

viewport = Viewport(type=Viewport.Type.Perspective)
viewport.zoom_all(size=(1400, 1000))
viewport.render_image(
    filename=output_path,
    size=(1400, 1000),
    frame=frame,
    background=(1.0, 1.0, 1.0),
    renderer=TachyonRenderer(),
)
"""
    proc = subprocess.run(
        [python_cmd, "-c", script, str(dump_path), str(output_path)],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    return {
        "returncode": proc.returncode,
        "output": proc.stdout,
    }


def _maybe_render_seed_ovito(
    *,
    run_dir: Path,
    seed: int,
    enabled: bool,
    python_cmd: Optional[str],
) -> Dict[str, Any]:
    if not enabled:
        return {"requested": False, "status": "disabled", "seed": seed}
    if python_cmd is None:
        return {
            "requested": True,
            "status": "skipped",
            "seed": seed,
            "reason": "ovito-python-not-found",
        }
    dump_path = _latest_dump_path(run_dir)
    if dump_path is None:
        return {
            "requested": True,
            "status": "skipped",
            "seed": seed,
            "reason": "no-dump-file-found",
        }
    output_path = run_dir / "ovito_snapshot.png"
    render = _render_ovito_snapshot(dump_path, output_path, python_cmd)
    if render["returncode"] != 0 or not output_path.exists():
        return {
            "requested": True,
            "status": "failed",
            "seed": seed,
            "dump_file": str(dump_path),
            "output_png": str(output_path),
            "reason": render["output"].strip() or "ovito-render-failed",
        }
    return {
        "requested": True,
        "status": "completed",
        "seed": seed,
        "dump_file": str(dump_path),
        "output_png": str(output_path),
    }

