from __future__ import annotations

import subprocess
from html import escape
from pathlib import Path
from typing import Any, Dict, Optional, Sequence


def _render_seed_comparison_svg(seed_runs: Sequence[Dict[str, Any]], output_path: Path) -> str:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for run in seed_runs:
        parsed = run.get("parsed_run") or {}
        rows.append(
            {
                "seed": int(run["seed"]),
                "status": str(run.get("status", "unknown")),
                "accepted_events": parsed.get("accepted_events"),
                "final_time": parsed.get("final_time"),
                "loop_time_seconds": parsed.get("loop_time_seconds"),
            }
        )

    width = 1200
    height = 760
    left = 90
    right = 40
    top = 70
    panel_height = 190
    panel_gap = 36
    slot_width = max((width - left - right) / max(len(rows), 1), 42)
    bar_width = max(slot_width * 0.58, 16)
    plot_width = width - left - right
    panels = [
        ("accepted_events", "Accepted events"),
        ("final_time", "Final time"),
        ("loop_time_seconds", "Loop time (s)"),
    ]

    def _fmt(value: Optional[float]) -> str:
        if value is None:
            return "—"
        numeric = float(value)
        if abs(numeric) >= 1000 or (abs(numeric) > 0 and abs(numeric) < 0.01):
            return f"{numeric:.3e}"
        return f"{numeric:.3f}".rstrip("0").rstrip(".")

    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        '<style>',
        'text { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: #111827; }',
        '.small { font-size: 12px; fill: #4b5563; }',
        '.title { font-size: 24px; font-weight: 700; }',
        '.subtitle { font-size: 13px; fill: #6b7280; }',
        '.panel-title { font-size: 16px; font-weight: 600; }',
        '</style>',
        f'<text x="{left}" y="38" class="title">KMC seed comparison</text>',
        f'<text x="{left}" y="58" class="subtitle">Generated by mietclaw for {len(rows)} seed runs</text>',
    ]

    for panel_index, (field, label) in enumerate(panels):
        y = top + panel_index * (panel_height + panel_gap)
        plot_bottom = y + panel_height
        values = [float(row[field]) for row in rows if row.get(field) is not None]
        max_value = max(values) if values else 1.0
        if max_value <= 0:
            max_value = 1.0

        svg.extend(
            [
                f'<text x="{left}" y="{y - 18}" class="panel-title">{escape(label)}</text>',
                f'<line x1="{left}" y1="{plot_bottom}" x2="{width - right}" y2="{plot_bottom}" stroke="#d1d5db" stroke-width="1"/>',
                f'<line x1="{left}" y1="{y}" x2="{left}" y2="{plot_bottom}" stroke="#d1d5db" stroke-width="1"/>',
            ]
        )
        for tick in range(5):
            tick_value = max_value * (4 - tick) / 4
            tick_y = y + panel_height * tick / 4
            svg.append(f'<line x1="{left}" y1="{tick_y:.1f}" x2="{width - right}" y2="{tick_y:.1f}" stroke="#f3f4f6" stroke-width="1"/>')
            svg.append(f'<text x="{left - 8}" y="{tick_y + 4:.1f}" text-anchor="end" class="small">{escape(_fmt(tick_value))}</text>')

        for index, row in enumerate(rows):
            slot_x = left + index * slot_width
            bar_x = slot_x + (slot_width - bar_width) / 2
            status = row["status"]
            color = "#2563eb" if status == "completed" else ("#f59e0b" if status == "warning" else "#dc2626")
            value = row.get(field)
            if value is None:
                bar_height = 0
            else:
                bar_height = (float(value) / max_value) * (panel_height - 18)
            bar_y = plot_bottom - bar_height
            svg.append(
                f'<rect x="{bar_x:.1f}" y="{bar_y:.1f}" width="{bar_width:.1f}" height="{max(bar_height, 2):.1f}" rx="4" fill="{color}" opacity="0.88"/>'
            )
            svg.append(
                f'<text x="{slot_x + slot_width / 2:.1f}" y="{plot_bottom + 18}" text-anchor="middle" class="small">seed {row["seed"]}</text>'
            )
            svg.append(
                f'<text x="{slot_x + slot_width / 2:.1f}" y="{max(bar_y - 6, y + 12):.1f}" text-anchor="middle" class="small">{escape(_fmt(value if value is not None else None))}</text>'
            )

    svg.append('</svg>')
    output_path.write_text("\n".join(svg) + "\n", encoding="utf-8")
    return str(output_path)


def _render_image_sequence_gif(
    image_paths: Sequence[Path],
    output_path: Path,
    *,
    python_cmd: str,
    duration_ms: int = 800,
) -> Dict[str, Any]:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    script = """
import sys
from PIL import Image

output_path = sys.argv[1]
duration_ms = int(sys.argv[2])
image_paths = sys.argv[3:]
frames = [Image.open(path).convert('RGBA') for path in image_paths]
first, rest = frames[0], frames[1:]
first.save(output_path, save_all=True, append_images=rest, duration=duration_ms, loop=0, disposal=2)
"""
    proc = subprocess.run(
        [python_cmd, "-c", script, str(output_path), str(duration_ms), *[str(path) for path in image_paths]],
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        check=False,
    )
    return {
        "returncode": proc.returncode,
        "output": proc.stdout,
    }

def _render_temperature_relationship_svg(
    *,
    rows: Sequence[Dict[str, Any]],
    output_path: Path,
    title: str,
    subtitle: str,
    x_key: str,
    y_key: str,
    x_label: str,
    y_label: str,
    y_error_key: Optional[str] = None,
    fit: Optional[Dict[str, float]] = None,
) -> str:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    points: list[Dict[str, Any]] = []
    for row in rows:
        if row.get(y_key) is None or row.get(x_key) is None:
            continue
        points.append(
            {
                "label": row.get("label") or f"{row.get('temperature_k', '')} K",
                "x": float(row[x_key]),
                "y": float(row[y_key]),
                "error": float(row[y_error_key]) if y_error_key and row.get(y_error_key) is not None else None,
            }
        )

    width = 1200
    height = 720
    left = 96
    right = 36
    top = 78
    bottom = 90
    plot_width = width - left - right
    plot_height = height - top - bottom

    if not points:
        output_path.write_text(
            "\n".join(
                [
                    f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
                    '<rect width="100%" height="100%" fill="#ffffff"/>',
                    '<text x="60" y="52" style="font: 700 24px -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif; fill:#111827;">'
                    + escape(title)
                    + "</text>",
                    '<text x="60" y="88" style="font: 14px -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif; fill:#6b7280;">No usable data points.</text>',
                    "</svg>",
                ]
            )
            + "\n",
            encoding="utf-8",
        )
        return str(output_path)

    xs = [point["x"] for point in points]
    ys = [point["y"] for point in points]
    y_candidates = []
    for point in points:
        error = point["error"] or 0.0
        y_candidates.extend([point["y"] - error, point["y"] + error])
    x_min = min(xs)
    x_max = max(xs)
    y_min = min(y_candidates)
    y_max = max(y_candidates)
    if x_max <= x_min:
        x_max = x_min + 1.0
    if y_max <= y_min:
        y_max = y_min + 1.0
    padding_y = max((y_max - y_min) * 0.08, 1.0e-12)
    y_min -= padding_y
    y_max += padding_y

    def _x_to_svg(value: float) -> float:
        return left + ((value - x_min) / (x_max - x_min)) * plot_width

    def _y_to_svg(value: float) -> float:
        return top + plot_height - ((value - y_min) / (y_max - y_min)) * plot_height

    def _fmt(value: float) -> str:
        if abs(value) >= 1000 or (abs(value) > 0 and abs(value) < 0.01):
            return f"{value:.3e}"
        return f"{value:.4f}".rstrip("0").rstrip(".")

    svg = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#ffffff"/>',
        '<style>',
        'text { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; fill: #111827; }',
        '.small { font-size: 12px; fill: #4b5563; }',
        '.title { font-size: 24px; font-weight: 700; }',
        '.subtitle { font-size: 13px; fill: #6b7280; }',
        '</style>',
        f'<text x="{left}" y="38" class="title">{escape(title)}</text>',
        f'<text x="{left}" y="58" class="subtitle">{escape(subtitle)}</text>',
        f'<line x1="{left}" y1="{top + plot_height}" x2="{width - right}" y2="{top + plot_height}" stroke="#d1d5db" stroke-width="1"/>',
        f'<line x1="{left}" y1="{top}" x2="{left}" y2="{top + plot_height}" stroke="#d1d5db" stroke-width="1"/>',
    ]

    for tick in range(5):
        y_value = y_min + ((4 - tick) / 4) * (y_max - y_min)
        y_svg = _y_to_svg(y_value)
        svg.append(f'<line x1="{left}" y1="{y_svg:.1f}" x2="{width - right}" y2="{y_svg:.1f}" stroke="#f3f4f6" stroke-width="1"/>')
        svg.append(f'<text x="{left - 8}" y="{y_svg + 4:.1f}" text-anchor="end" class="small">{escape(_fmt(y_value))}</text>')
    for tick in range(5):
        x_value = x_min + (tick / 4) * (x_max - x_min)
        x_svg = _x_to_svg(x_value)
        svg.append(f'<line x1="{x_svg:.1f}" y1="{top}" x2="{x_svg:.1f}" y2="{top + plot_height}" stroke="#f9fafb" stroke-width="1"/>')
        svg.append(f'<text x="{x_svg:.1f}" y="{top + plot_height + 22}" text-anchor="middle" class="small">{escape(_fmt(x_value))}</text>')

    if fit is not None:
        fit_start = fit["slope"] * x_min + fit["intercept"]
        fit_end = fit["slope"] * x_max + fit["intercept"]
        svg.append(
            f'<line x1="{_x_to_svg(x_min):.1f}" y1="{_y_to_svg(fit_start):.1f}" '
            f'x2="{_x_to_svg(x_max):.1f}" y2="{_y_to_svg(fit_end):.1f}" '
            'stroke="#93c5fd" stroke-width="2" stroke-dasharray="8 6"/>'
        )

    polyline = " ".join(f"{_x_to_svg(point['x']):.1f},{_y_to_svg(point['y']):.1f}" for point in points)
    svg.append(f'<polyline fill="none" stroke="#2563eb" stroke-width="3" points="{polyline}"/>')

    for point in points:
        x_svg = _x_to_svg(point["x"])
        y_svg = _y_to_svg(point["y"])
        error = point["error"]
        if error:
            high = _y_to_svg(point["y"] + error)
            low = _y_to_svg(point["y"] - error)
            svg.append(f'<line x1="{x_svg:.1f}" y1="{high:.1f}" x2="{x_svg:.1f}" y2="{low:.1f}" stroke="#2563eb" stroke-width="1.5"/>')
            svg.append(f'<line x1="{x_svg - 6:.1f}" y1="{high:.1f}" x2="{x_svg + 6:.1f}" y2="{high:.1f}" stroke="#2563eb" stroke-width="1.5"/>')
            svg.append(f'<line x1="{x_svg - 6:.1f}" y1="{low:.1f}" x2="{x_svg + 6:.1f}" y2="{low:.1f}" stroke="#2563eb" stroke-width="1.5"/>')
        svg.append(f'<circle cx="{x_svg:.1f}" cy="{y_svg:.1f}" r="5.5" fill="#ffffff" stroke="#1d4ed8" stroke-width="2"/>')
        svg.append(f'<text x="{x_svg:.1f}" y="{max(y_svg - 10, top + 14):.1f}" text-anchor="middle" class="small">{escape(str(point["label"]))}</text>')

    svg.append(f'<text x="{left + plot_width / 2:.1f}" y="{height - 26}" text-anchor="middle" class="small">{escape(x_label)}</text>')
    svg.append(
        f'<text x="24" y="{top + plot_height / 2:.1f}" text-anchor="middle" transform="rotate(-90 24 {top + plot_height / 2:.1f})" class="small">{escape(y_label)}</text>'
    )
    svg.append("</svg>")
    output_path.write_text("\n".join(svg) + "\n", encoding="utf-8")
    return str(output_path)

