import csv
import json
import math
from pathlib import Path
from typing import Dict, Iterable, List

from .constants import BOLTZMANN_EV_PER_K


class TransformError(ValueError):
    pass


def compute_rate_hz(barrier_ev: float, prefactor_hz: float, temperature_k: float) -> float:
    return prefactor_hz * math.exp(-barrier_ev / (BOLTZMANN_EV_PER_K * temperature_k))


def compile_event_table(barrier_payload: Dict, temperature_k: float) -> List[Dict]:
    events = barrier_payload.get("events", [])
    if not events:
        raise TransformError("No barrier events found")

    default_prefactor = float(barrier_payload.get("attempt_frequency_hz", 1.0e13))
    rows: List[Dict] = []
    for event in events:
        species = event.get("species")
        barrier_ev = float(event["barrier_ev"])
        prefactor_hz = float(event.get("prefactor_hz", default_prefactor))
        rate_hz = compute_rate_hz(barrier_ev, prefactor_hz, temperature_k)
        row = {
            "event_id": event.get("event_id", f"event_{len(rows)}"),
            "species": species,
            "pathway": event.get("pathway", "unspecified"),
            "barrier_ev": barrier_ev,
            "prefactor_hz": prefactor_hz,
            "temperature_k": float(temperature_k),
            "rate_hz": rate_hz,
            "kmc_barrier_key": event.get("kmc_barrier_key", species),
            "source": barrier_payload.get("source", "unknown"),
        }
        rows.append(row)
    return rows


def synthetic_event_rows(precomputed_barriers: Dict[str, float], temperature_k: float, prefactor_hz: float = 1.0e13) -> List[Dict]:
    payload = {
        "source": "precomputed-barrier-map",
        "attempt_frequency_hz": prefactor_hz,
        "events": [
            {
                "event_id": f"precomputed_{species}",
                "species": species,
                "barrier_ev": barrier,
                "prefactor_hz": prefactor_hz,
                "pathway": "precomputed",
            }
            for species, barrier in precomputed_barriers.items()
        ],
    }
    return compile_event_table(payload, temperature_k)


def write_event_table_csv(rows: Iterable[Dict], path: Path) -> None:
    rows = list(rows)
    fieldnames = [
        "event_id",
        "species",
        "pathway",
        "barrier_ev",
        "prefactor_hz",
        "temperature_k",
        "rate_hz",
        "kmc_barrier_key",
        "source",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)


def write_json(path: Path, payload: Dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def derive_kmc_barrier_map(rows: Iterable[Dict], tolerance: float = 1e-12) -> Dict[str, float]:
    barrier_map: Dict[str, float] = {}
    for row in rows:
        key = row["kmc_barrier_key"]
        barrier_ev = float(row["barrier_ev"])
        if key in barrier_map and abs(barrier_map[key] - barrier_ev) > tolerance:
            raise TransformError(
                f"Current KMC adapter only supports one barrier per kmc key. key={key}, values={barrier_map[key]} and {barrier_ev}"
            )
        barrier_map[key] = barrier_ev
    return barrier_map


def stage_support_file(source: str, destination_dir: Path) -> str:
    source_path = Path(source)
    if not source_path.exists():
        raise FileNotFoundError(f"Support file not found: {source_path}")
    destination_dir.mkdir(parents=True, exist_ok=True)
    staged = destination_dir / source_path.name
    staged.write_bytes(source_path.read_bytes())
    return staged.name


def render_kmc_input(template: Dict, barrier_map: Dict[str, float], temperature_k: float, cluster_ref: str = None) -> str:
    lattice = template["lattice"]
    region_block = " ".join(str(v) for v in template["region_block"])
    create_sites_value = template.get("create_sites_value", 1)
    neighbour_cutoff = template.get("neighbour_cutoff", 0.9)
    species_order = template.get("species_order") or sorted(barrier_map)
    masses = template.get("species_masses", {})
    mass_values = " ".join(str(masses[species]) for species in species_order if species in masses)
    radius = template.get("diffusion_radius_lattice_units", 1.0)

    lines = [
        "# Generated by miet-claw",
        f"seed\t\t {template.get('seed', 2001)}",
        "app_style vacancy",
        "",
        "dimension\t 3",
        f"lattice      {lattice['type']}  {lattice['constant']}",
        f"region\t\t box block {region_block}",
        "create_box\t box",
        f"create_sites box value site {create_sites_value}",
        "",
    ]

    for item in template.get("initial_fractions", []):
        lines.append(f"set              {item['site']} value {item['value']} fraction {item['fraction']}")

    lines.extend(["", f"nei {neighbour_cutoff}", ""])

    for species in species_order:
        if species not in barrier_map:
            raise TransformError(f"Missing barrier for species '{species}'")
        lines.append(f"barrier   {species} {barrier_map[species]:.6f}")

    lines.extend([
        "",
        template["potential_line"],
        "",
        "solve_style      tree",
        f"temperature\t     {temperature_k}",
        "diag_style       energy stats yes",
    ])

    if mass_values:
        lines.extend(
            [
                "",
                "plugin diffusion",
                f"config_plugin diffusion mass {len(species_order)} {mass_values} radius {radius} on-decomposed stop log file diffusion.csv",
            ]
        )
        if cluster_ref:
            lines.append(f"replace {cluster_ref}")

    lines.extend(
        [
            "",
            f"sector           yes tstop {template.get('sector_tstop', '6.0e-6')}",
            f"stats            {template.get('stats_interval', '1e-5')}",
            f"dump             1 text {template.get('dump_interval', '0.2')} *.k.dump.vacancy id site x y z",
            f"run              {template.get('run_until', '1e-4')}",
            "",
        ]
    )
    return "\n".join(lines)
